# Generated by Django 3.0.7 on 2020-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200609_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfirstname', models.CharField(max_length=20)),
                ('slastname', models.CharField(max_length=20)),
                ('semail', models.CharField(max_length=40)),
                ('sphone', models.IntegerField()),
                ('scountry', models.CharField(max_length=40)),
                ('scourses', models.ManyToManyField(blank=True, related_name='students', to='shop.Course')),
            ],
        ),
    ]
